//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltBet.BalanceServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BalanceServiceReference.IBalanceManager")]
    public interface IBalanceManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBalanceManager/GetCurrentUserAssets", ReplyAction="http://tempuri.org/IBalanceManager/GetCurrentUserAssetsResponse")]
        AltBet.Exchange.UserAssets GetCurrentUserAssets(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBalanceManager/GetCurrentUserAssets", ReplyAction="http://tempuri.org/IBalanceManager/GetCurrentUserAssetsResponse")]
        System.Threading.Tasks.Task<AltBet.Exchange.UserAssets> GetCurrentUserAssetsAsync(string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBalanceManagerChannel : AltBet.BalanceServiceReference.IBalanceManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BalanceManagerClient : System.ServiceModel.ClientBase<AltBet.BalanceServiceReference.IBalanceManager>, AltBet.BalanceServiceReference.IBalanceManager {
        
        public BalanceManagerClient() {
        }
        
        public BalanceManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BalanceManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BalanceManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BalanceManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AltBet.Exchange.UserAssets GetCurrentUserAssets(string userName) {
            return base.Channel.GetCurrentUserAssets(userName);
        }
        
        public System.Threading.Tasks.Task<AltBet.Exchange.UserAssets> GetCurrentUserAssetsAsync(string userName) {
            return base.Channel.GetCurrentUserAssetsAsync(userName);
        }
    }
}
