/**
 * Created by Htmlbook on 27.01.2017.
 */
export const TRADER_ON_SOCKET_MESSAGE = 'TRADER_ON_SOCKET_MESSAGE';
export const TRADER_ON_QUANTITY_CHANGE = 'TRADER_ON_QUANTITY_CHANGE';
export const TRADER_ON_SPREAD_CHANGE = 'TRADER_ON_SPREAD_CHANGE';
export const TRADER_ON_ADD_ORDER = 'TRADER_ON_ADD_ORDER';
export const TRADER_ON_DELETE_ORDER = 'TRADER_ON_DELETE_ORDER';
