/**
 * Created by Htmlbook on 28.12.2016.
 */
export const DEPOSIT_QUANTITY_CHANGE = 'DEPOSIT_QUANTITY_CHANGE';
export const DEPOSIT_PRICE_PLAN_CHANGE = 'DEPOSIT_PRICE_PLAN_CHANGE';
export const DEPOSIT_PERIOD_CHANGE = 'DEPOSIT_PERIOD_CHANGE';
export const DEPOSIT_FORM_SUBMIT = 'DEPOSIT_FORM_SUBMIT';