export const ON_CHART_MOUNT = 'ON_CHART_MOUNT';
export const ON_CHART_TYPE_CHANGE = 'ON_CHART_TYPE_CHANGE';

export const ON_SOCKET_MESSAGE = 'ON_EP_SOCKET_MESSAGE';
export const ON_TRADE_ONOFF = 'ON_TRADE_ONOFF_EP';
