/**
 * Created by Htmlbook on 22.12.2016.
 */
export const ON_YOUR_ORDER_SOCKET_MESSAGE = 'ON_YOUR_ORDER_SOCKET_MESSAGE';
export const ON_YOUR_ORDER_DELETE = 'ON_YOUR_ORDER_DELETE';
export const ON_YOUR_ORDER_GROUP_INDEX = 'ON_YOUR_ORDER_GROUP_INDEX';