/**
 * Created by Htmlbook on 28.12.2016.
 */
export const DEPOSIT_APPROVE = 'DEPOSIT_APPROVE';
export const DEPOSIT_QUANTITY_CHANGE = 'DEPOSIT_QUANTITY_CHANGE';
export const DEPOSIT_PRICE_PLAN_CHANGE = 'DEPOSIT_PRICE_PLAN_CHANGE';
export const DEPOSIT_PERIOD_CHANGE = 'DEPOSIT_PERIOD_CHANGE';
export const DEPOSIT_QUANTITY_VALIDATE = 'DEPOSIT_QUANTITY_VALIDATE';
export const DEPOSIT_SOCKET_MESSAGE = 'DEPOSIT_SOCKET_MESSAGE';