export const SETTING_ON_FILE_LOAD = 'GV_SETTING_ON_FILE_LOAD';
export const SETTING_LOAD_FILE_ERROR = 'GV_SETTING_LOAD_FILE_ERROR';
export const SETTING_CHANGE_PROGRESS_BAR = 'GV_SETTING_CHANGE_PROGRESS_BAR';
