/**
 * Created by Htmlbook on 14.01.2017.
 */
export const VALIDATION_ON_INPUT_CHANGE = 'VALIDATION_ON_INPUT_CHANGE';
export const VALIDATION_ON_INITIAL_VALUES = 'VALIDATION_ON_INITIAL_VALUES';
export const VALIDATION_ON_FORM_INITIAL = 'VALIDATION_ON_FORM_INITIAL';
export const VALIDATION_ON_CHECK_INPUT = 'VALIDATION_ON_CHECK_INPUT';
export const VALIDATION_ON_INPUT_VALIDATION = 'VALIDATION_ON_INPUT_VALIDATION';
export const VALIDATION_ON_FORM_SUBMIT = 'VALIDATION_ON_FORM_SUBMIT';

