/**
 * Created by Htmlbook on 20.01.2017.
 */
// export const DEPOSIT_QUANTITY_CHANGE = 'DEPOSIT_QUANTITY_CHANGE';
// export const DEPOSIT_PRICE_PLAN_CHANGE = 'DEPOSIT_PRICE_PLAN_CHANGE';
// export const DEPOSIT_PERIOD_CHANGE = 'DEPOSIT_PERIOD_CHANGE';
// export const DEPOSIT_QUANTITY_VALIDATE = 'DEPOSIT_QUANTITY_VALIDATE';
// export const DEPOSIT_SOCKET_MESSAGE = 'DEPOSIT_SOCKET_MESSAGE';
export const TRANS_HISTORY_SET_PAYMENT_FILTER = 'TRANS_HISTORY_SET_PAYMENT_FILTER';
export const TRANS_HISTORY_SET_DATE_FILTER = 'TRANS_HISTORY_SET_DATE_FILTER';