// export const ON_LOAD = 'ON_SB_LOAD';
export const ON_SIDEBAR_LOAD = 'ON_SIDEBAR_LOAD';
export const ALLOW_AT_CH = 'ALLOW_AT_CH';
export const ON_TRADER_ON = 'ON_SB_TRADER_ON';
export const ON_AUTO_TRADE = 'ON_AUTO_TRADE';
export const ON_TAB_SWITCH = 'ON_TAB_SWITCH';
export const ON_ACTIVE_SYMBOL_CHANGED = 'ON_ACTIVE_SYMBOL_CHANGED';
export const ON_SIDEBAR_ODD_SYS_CHANGE = 'ON_SIDEBAR_ODD_SYS_CHANGE';
