/**
 * Created by Htmlbook on 22.12.2016.
 */
export const ON_DEFAULT_ORDER_DELETE = 'ON_DEFAULT_ORDER_DELETE';
export const ON_DEFAULT_ORDER_TYPE_CHANGE = 'ON_DEFAULT_ORDER_TYPE_CHANGE';
export const ON_DEFAULT_ORDER_CREATE = 'ON_DEFAULT_ORDER_CREATE';
export const ON_DEFAULT_ORDER_AJAX_SEND = 'ON_DEFAULT_ORDER_AJAX_SEND';
export const ON_TAB_MIRROR_CHANGE = 'ON_TAB_MIRROR_CHANGE';
