/**
 * Created by Htmlbook on 28.12.2016.
 */
export const WITHDRAW_APPROVE = 'WITHDRAW_APPROVE';
export const WITHDRAW_QUANTITY_CHANGE = 'WITHDRAW_QUANTITY_CHANGE';
export const WITHDRAW_QUANTITY_VALIDATE = 'WITHDRAW_QUANTITY_VALIDATE';
export const WITHDRAW_SOCKET_MESSAGE = 'WITHDRAW_SOCKET_MESSAGE';