export const MP_ON_POS_PRICE_CLICK = 'MP_ON_POS_PRICE_CLICK';
export const MP_ON_SOCKET_MESSAGE = 'MP_ON_MAINPAGE_SOCKET_MESSAGE';
export const MP_CHART_ON_SOCKET_MESSAGE = 'MP_CHART_ON_MAINPAGE_SOCKET_MESSAGE';
export const MP_ON_BASIC_MODE_CH = 'MP_ON_BASIC_MODE_CH_MP';
export const MP_ON_CHANGE_SUBSCRIBING = 'MP_ON_CHANGE_SUBSCRIBING';
export const MP_TRAIDER_MODE_CH = 'MP_TRAIDER_MODE_CH_MP';
export const MP_ON_CHANGE_ORDER_VISABLT = 'MP_ON_CHANGE_ORDER_VISABLT';
export const MP_ON_CHANGE_ORDER_PRICE = 'MP_ON_CHANGE_ORDER_PRICE';

