/**
 * Created by Htmlbook on 22.12.2016.
 */
export const ON_YOUR_ORDER_SOCKET_MESSAGE = 'ON_YOUR_ORDER_SOCKET_MESSAGE';
export const ON_YOUR_ORDER_DELETE = 'ON_YOUR_ORDER_DELETE';
export const ON_YOUR_ORDER_GROUP_SYMBOL = 'ON_YOUR_ORDER_GROUP_SYMBOL';
export const ON_YOUR_CHANGE_ACTIVE_EVENT = 'ON_YOUR_CHANGE_ACTIVE_EVENT';