/**
 * Created by Vlasakh on 21.04.2017.
 */

export const ON_ADD_TEAM_PLAYER = "ON_NFE_ADD_TEAM_PLAYER" ;
export const ON_ADD_TEAM_UP_PLAYER = "ON_NFE_ADD_TEAM_UP_PLAYER" ;
export const ON_DEL_TEAM_PLAYER = "ON_NFE_DEL_TEAM_PLAYER" ;
export const ON_CHANGE_EVENT = "ON_NFE_CHANGE_EVENT" ;
export const ON_ENTER_PPG = "ON_NFE_ENTER_PPG" ;
export const ON_CHANGE_EVENTS_PERIOD = "ON_NFE_CHANGE_EVENT_PERIODS" ;
export const ON_ADD_TEAM_PLAYER_RESERVE = "ON_NFE_TEAM_PLAYER_RESERVE" ;
export const ON_SET_CURR_TEAM = "ON_NFE_SET_CURR_TEAM" ;
export const ON_ADD_TEAM_PLAYER_VARIABLE = "ON_NFE_ON_ADD_TEAM_PLAYER_VARIABLE" ;
export const ON_CH_TEAM_NAME = "ON_NFE_CH_TEAM_NAME" ;
export const ON_GEN_TEAM_NAME = "ON_NFE_GEN_TEAM_NAME" ;
export const ON_CH_FORM_DATA = "ON_NFE_CH_FORM_DATA" ;
export const ON_GEN_FULL_NAME = "ON_NFE_GEN_FULL_NAME" ;
export const ON_GEN_URL = "ON_NFE_GEN_URL" ;
export const ON_SAVE_EVENT_OK = "ON_NFE_SAVE_EVENT_OK" ;
export const ON_SAVE_EVENT_FAIL = "ON_NFE_SAVE_EVENT_FAIL " ;
export const ON_ADD_TEAM_DEFENCE = "NFE_ON_ADD_TEAM_DEFENCE " ;
export const ON_REM_TEAM_DEFENCE = "NFE_ON_REM_TEAM_DEFENCE " ;
export const AFTER_CATEGORY_ADDED = "NFE_AFTER_CATEGORY_ADDED " ;