/**
 * Created by Vlasakh on 21.04.2017.
 */

export const ON_ADD_TEAM_PLAYER = "ON_NFE_ADD_TEAM_PLAYER" ;
export const ON_ADD_TEAM_UP_PLAYER = "ON_NFE_ADD_TEAM_UP_PLAYER" ;
export const ON_DEL_TEAM_PLAYER = "ON_NFE_DEL_TEAM_PLAYER" ;
export const ON_CHANGE_EVENT = "ON_NFE_CHANGE_EVENT" ;
export const ON_ENTER_PPG = "ON_NFE_ENTER_PPG" ;
export const ON_CHANGE_EVENTS_PERIOD = "ON_NFE_CHANGE_EVENT_PERIODS" ;
export const ON_ADD_TEAM_PLAYER_RESERVE = "ON_NFE_TEAM_PLAYER_RESERVE" ;
export const ON_SET_CURR_TEAM = "ON_NFE_SET_CURR_TEAM" ;
export const ON_ADD_TEAM_PLAYER_VARIABLE = "ON_NFE_ON_ADD_TEAM_PLAYER_VARIABLE" ;